name: Validation

on:
  pull_request:
    branches:
      - main
    paths:
      - igs/*/sushi-config.yaml
      - igs/*/fsh/input
  workflow_dispatch:

env:
  IG: MessagingCore

jobs:
  fhir_validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # This step can be omitted when firely-terminal-pipeline has added support for SUSHI.
      - name: 🍣 Run SUSHI
        run: npm install fsh-sushi && sushi igs/${{ env.IG }}

      # Uses Firely's action to run the official Java FHIR Validator because it gives a prettified output.
      # Doc: https://github.com/FirelyTeam/firely-terminal-pipeline
      - name: 🔥 Run FHIR Validator
        uses: FirelyTeam/firely-terminal-pipeline@v0.2.1
        with:
          SIMPLIFIER_USERNAME: N/A
          SIMPLIFIER_PASSWORD: N/A
          PATH_TO_CONFORMANCE_RESOURCES: igs/${{ env.IG }}/fsh-generated/resources
          PATH_TO_EXAMPLES: igs/${{ env.IG }}/fsh-generated/resources
          DOTNET_VALIDATION_ENABLED: false
          JAVA_VALIDATION_ENABLED: true
