name: Validation

on:
  pull_request:
    branches:
      - main
    paths:
      - igs/*/sushi-config.yaml
      - igs/*/fsh/input
  workflow_dispatch:

env:
  IG: MessagingCore

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cache package-cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.fhir/packages
          key: fhir-packages

      # Builds the .fsh files into FHIR .json resources.
      # Doc: https://fshschool.org/docs/sushi/running
      - name: 🍣 Run SUSHI
        run: |
          npm install -g fsh-sushi
          sushi igs/${{ env.IG }} --snapshot --out .
