name: Validation

on:
  pull_request:
    branches:
      - main
    paths:
      - igs/*/sushi-config.yaml
      - igs/*/fsh/input
  workflow_dispatch:

env:
  IG: MessagingCore

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cache package-cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.fhir
          key: fhir-packages

      # Builds the .fsh files into FHIR .json resources.
      # Doc: https://fshschool.org/docs/sushi/running
      - name: 🍣 Run SUSHI
        run: |
          npm install -g fsh-sushi
          sushi igs/${{ env.IG }} --snapshot --out .

      # Downloads and runs the official FHIR Validator.
      # Doc: https://confluence.hl7.org/display/FHIR/Using+the+FHIR+Validator
      - name: 🔥 Run FHIR Validator
        run: |
          wget -q https://github.com/hapifhir/org.hl7.fhir.core/releases/latest/download/validator_cli.jar
          java -jar validator_cli.jar fsh-generated/resources -version 4.0 -ig fsh-generated/resources
