name: Validation

on:
  pull_request:
    branches:
      - main
    paths:
      - igs/*/sushi-config.yaml
      - igs/*/fsh/input
  workflow_dispatch:

env:
  IG: MessagingCore

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # This step can be omitted when firely-terminal-pipeline has added support for SUSHI.
      - name: 🍣 Run SUSHI
        run: npm install -g fsh-sushi && sushi igs/${{ env.IG }}

      # Downloads and runs the official FHIR Validator.
      # Doc: https://confluence.hl7.org/display/FHIR/Using+the+FHIR+Validator
      - name: 🔥 Run FHIR Validator
        run: |
          wget -q https://github.com/hapifhir/org.hl7.fhir.core/releases/latest/download/validator_cli.jar
          java -jar validator_cli.jar -version 4.0 -ig igs/${{ env.IG }}/fsh-generated/resources igs/${{ env.IG }}/fsh-generated/resources
