name: Test

on:
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        app:
          - hops-api
    env:
      IMAGE: ghcr.io/navikt/${{ matrix.app }}:e564a55271271bf3aecadf263ba61d6a00014f7e
    runs-on: ubuntu-latest
    steps:
      - name: ❔ Check if image exists
        id: check_image
        run: |
          if [[ $(docker manifest inspect ${{ env.IMAGE }}) ]]; then
            echo "::set-output name=exists::true"
          else
            echo "::set-output name=exists::false"
          fi

      - name: print
        if: ${{ steps.check_image.outputs.exists == 'true'}}
        run: |
          echo "Image exists!"

      - name: print
        if: ${{ steps.check_image.outputs.exists == 'false'}}
        run: |
          echo "Image does not exists!"