name: Test

on:
  workflow_dispatch:
    inputs:
      app:
        description: 'Name of app to deploy, e.g. hops-api'
        required: true

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Check if changes are relevant
        id: diff
        uses: tj-actions/changed-files@v1.1.2
        with:
          files: |
            igs/MessagingCore/*
      
      - name: Check if app should be deployed
        run: |
          echo "DEPLOY=${{ steps.diff.outputs.any_changed == 'true' || github.event.inputs.app == matrix.app }}" >> $GITHUB_ENV

      - name: changes?
        run: |
          echo ${{ steps.diff.outputs.any_changed }}
          echo ${{ steps.diff.outputs.all_changed_and_modified_files }}

      - if: ${{ env.DEPLOY == 'true' }}
        run: echo "Hello world!"

      - if: ${{ env.DEPLOY == 'false' }}
        run: echo "Negative Hello world!"        