name: Test

on:
  push:
    branches: [main]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Check if changes are relevant
        id: diff
        uses: tj-actions/changed-files@v1.1.2
        with:
          files: |
            igs/MessagingCore/*
      
      - name: changes?
        run: |
          echo ${{ steps.diff.outputs.any_changed }}
          echo ${{ steps.diff.outputs.all_changed_and_modified_files }}