name: Update package feed

on:
  release:
    types:
      - released
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Creates a new package-feed.xml from releases using the Liquid template.
      - name: 📃 Create package feed
        run: |
          npm install liquidjs
          cat package-feed.liquid | npx liquidjs '{"releases":$(wget -q -O - https://api.github.com/repos/navikt/fhir/releases)}' > package-feed.xml

      # Publishes the generated package-feed.xml to a seperate branch in order to host it using GitHub-Pages.
      # This will overwrite the currently published package-feed.xml.
      - name: 🚀 Deploy to GitHub-Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          exclude_assets: '**, !package-feed.xml'
          commit_message: 'Updated package-feed.xml'