name: Update package-feed.xml

on:
  release:
    types:
      - released
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Creates a new package-feed.xml from releases using the Liquid template.
      - name: 📃 Create package feed
        run: |
          npm install -g liquidjs
          echo '{"releases":' > input.json
          wget -q -O - https://api.github.com/repos/navikt/fhir/releases >> input.json
          echo '}' >> input.json
          mkdir output
          cat package-feed.liquid | npx liquidjs input.json > output/package-feed.xml

      # Publishes the package-feed.xml to a seperate branch in order to host it using GitHub-Pages.
      # This will overwrite the currently published package-feed.xml.
      - name: 🚀 Deploy to GitHub-Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: output
          commit_message: 'Updated package-feed.xml'
          keep_files: true
